<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[STEP1]]>
    </line>
    <line>
      <![CDATA[STEP2]]>
    </line>
    <line>
      <![CDATA[STEP3]]>
    </line>
    <line>
      <![CDATA[STEP4]]>
    </line>
    <line>
      <![CDATA[STEP5]]>
    </line>
    <line>
      <![CDATA[STEP6]]>
    </line>
    <line>
      <![CDATA[STEP7]]>
    </line>
    <line>
      <![CDATA[STEP8]]>
    </line>
    <line>
      <![CDATA[STEP9]]>
    </line>
    <line>
      <![CDATA[STEP10]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="27015" started-at="2017-03-29T05:43:56Z" finished-at="2017-03-29T05:44:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27015" started-at="2017-03-29T05:43:56Z" finished-at="2017-03-29T05:44:23Z">
      <class name="testweb.Test1">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testweb.Test1@490ab905]" name="setUp" is-config="true" duration-ms="4591" started-at="2017-03-29T11:13:57Z" finished-at="2017-03-29T11:14:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginVerification(java.lang.String, java.lang.String)[pri:0, instance:testweb.Test1@490ab905]" name="loginVerification" duration-ms="1867" started-at="2017-03-29T11:14:01Z" data-provider="Authentication" finished-at="2017-03-29T11:14:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[goel199321]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[bharatpur]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA["By.xpath: //input[@type='password']" is not present. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: "By.xpath: //input[@type='password']" is not present. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.gslab.services.Services.assertAndVerifyElement(Services.java:59)
	at com.gslab.services.Services.assertElementAndType(Services.java:84)
	at pages.Home.loginVerification(Home.java:63)
	at testweb.Test1.loginVerification(Test1.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[STEP1]]>
            </line>
            <line>
              <![CDATA[STEP2]]>
            </line>
            <line>
              <![CDATA[STEP3]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginVerification -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testweb.Test1@490ab905]" name="tearDown" is-config="true" duration-ms="309" started-at="2017-03-29T11:14:03Z" finished-at="2017-03-29T11:14:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:testweb.Test1@490ab905]" name="setUp" is-config="true" duration-ms="3838" started-at="2017-03-29T11:14:04Z" finished-at="2017-03-29T11:14:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginVerification(java.lang.String, java.lang.String)[pri:0, instance:testweb.Test1@490ab905]" name="loginVerification" duration-ms="1815" started-at="2017-03-29T11:14:07Z" data-provider="Authentication" finished-at="2017-03-29T11:14:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[goel199321]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[bharatpur]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA["By.xpath: //input[@type='password']" is not present. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: "By.xpath: //input[@type='password']" is not present. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.gslab.services.Services.assertAndVerifyElement(Services.java:59)
	at com.gslab.services.Services.assertElementAndType(Services.java:84)
	at pages.Home.loginVerification(Home.java:63)
	at testweb.Test1.loginVerification(Test1.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[STEP4]]>
            </line>
            <line>
              <![CDATA[STEP5]]>
            </line>
            <line>
              <![CDATA[STEP6]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginVerification -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testweb.Test1@490ab905]" name="tearDown" is-config="true" duration-ms="156" started-at="2017-03-29T11:14:09Z" finished-at="2017-03-29T11:14:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:testweb.Test1@490ab905]" name="setUp" is-config="true" duration-ms="3536" started-at="2017-03-29T11:14:09Z" finished-at="2017-03-29T11:14:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginVerification(java.lang.String, java.lang.String)[pri:0, instance:testweb.Test1@490ab905]" name="loginVerification" duration-ms="9798" started-at="2017-03-29T11:14:13Z" data-provider="Authentication" finished-at="2017-03-29T11:14:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[goel1993420]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[bharatpur0]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[STEP7]]>
            </line>
            <line>
              <![CDATA[STEP8]]>
            </line>
            <line>
              <![CDATA[STEP9]]>
            </line>
            <line>
              <![CDATA[STEP10]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginVerification -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testweb.Test1@490ab905]" name="tearDown" is-config="true" duration-ms="202" started-at="2017-03-29T11:14:23Z" finished-at="2017-03-29T11:14:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testweb.Test1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
